version: "3.3"

services:
  mrms-client:
    build: ./
    image: lamstroning/mrms-front
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true

networks:
  default:
    external:
      name: sqsnet
